allow-lan: true
bind-address: '*'
log-level: error
mixed-port: 7890
ipv6: false
dns:
  enable: true
  listen: '0.0.0.0:53'
  ipv6: false
  tcp: true
  default-nameserver:
    - 8.8.8.8
  enhanced-mode: redir-host
  nameserver:
    - 8.8.8.8
  doh-proxy: "http://127.0.0.1:7890"
  fallback:
    - 'https://1.1.1.1/dns-query'
    - 'https://1.0.0.1/dns-query'
    - 'https://9.9.9.9/dns-query'
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - '+.v2ex.com'
      - '+.gstatic.com'
      - '+.linkedin.com'
proxies:
proxy-groups:
  - name: auto
    type: load-balance
    proxies:
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
rules:
  - 'DOMAIN-SUFFIX,google.com,auto'
  - 'DOMAIN-KEYWORD,google,auto'
  - 'DOMAIN,google.com,auto'
  - 'DOMAIN-SUFFIX,ad.com,REJECT'
  - 'DST-PORT,9954,REJECT'
  - 'DST-PORT,9955,REJECT'
  - 'IP-CIDR,127.0.0.0/8,DIRECT'
  - 'GEOIP,CN,DIRECT'
  - 'MATCH,auto'
